[package]
name = "rusty_gb"
version = "1.3.0"
authors = ["bfsgr <bfsgr.code@protonmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.17"
