[package]
name = "librustygb-ffi"
version = "1.3.0"
authors = ["bfsgr <bfsgr.code@protonmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[lib]
name = "rustygb_c"
crate-type = ["cdylib"]

[dependencies]
librustygb = {path = "../lib-rustygb"}
libc = "0.2"